"""Communication protocol simulation package."""

from .channels import (
    AdversarialChannel,
    ChannelDeliveryError,
    NoisyChannel,
    PerfectChannel,
    ReorderingChannel,
    TransportChannel,
)
from .events import EventLogger, ProtocolEvent
from .protocols import (
    BroadcastRecord,
    BroadcastResult,
    GroupHandshakeResult,
    GroupProtocolRunSummary,
    GroupRekeyResult,
    HandshakeResult,
    ProtocolRunSummary,
    TranscriptReplayResult,
    broadcast_group_message,
    export_group_transcript,
    perform_group_key_agreement,
    rekey_group_membership,
    replay_group_broadcast,
    replay_group_transcript,
    run_group_key_agreement_batch,
    perform_secure_key_agreement,
    run_key_agreement_batch,
)
from .state import HandshakePhase, ProtocolState, SessionState

__all__ = [
    "AdversarialChannel",
    "ChannelDeliveryError",
    "BroadcastRecord",
    "BroadcastResult",
    "EventLogger",
    "GroupHandshakeResult",
    "GroupProtocolRunSummary",
    "GroupRekeyResult",
    "HandshakePhase",
    "HandshakeResult",
    "ProtocolState",
    "ProtocolRunSummary",
    "NoisyChannel",
    "PerfectChannel",
    "ProtocolEvent",
    "ReorderingChannel",
    "SessionState",
    "TranscriptReplayResult",
    "TransportChannel",
    "broadcast_group_message",
    "export_group_transcript",
    "perform_group_key_agreement",
    "perform_secure_key_agreement",
    "rekey_group_membership",
    "replay_group_broadcast",
    "replay_group_transcript",
    "run_group_key_agreement_batch",
    "run_key_agreement_batch",
]
